CREATE DATABASE ONEMIN
USE [ONEMIN]

 CREATE TABLE UsersCategory
 (
  Id INT IDENTITY(1,1) PRIMARY KEY
  ,Name VARCHAR(50)
 )
 
 CREATE TABLE PayType
 (
  Id INT IDENTITY(1,1) PRIMARY KEY
  ,Name VARCHAR(50)
 )
 
 CREATE TABLE Users
(
  ID INT IDENTITY(1,1) PRIMARY KEY
  ,FIRSTNAME VARCHAR(50)
  ,LASTNAME VARCHAR(50)
  ,EMAILID VARCHAR(50)
  ,MOBILENO VARCHAR(10) CONSTRAINT CK_Users_MOBILENO check (MOBILENO like '[0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9]')
  ,CATEGORYID INT CONSTRAINT FK_UsersCategoryUser FOREIGN KEY (CATEGORYID) REFERENCES UsersCategory(ID)
)
